FROM node:22-alpine
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

WORKDIR /app

RUN corepack enable && chown -R appuser:appgroup /app

COPY --chown=appuser:appgroup package.json pnpm-lock.yaml ./
USER appuser
RUN pnpm install --frozen-lockfile

EXPOSE 4200

CMD ["pnpm", "run", "start:docker"]
