sonar.projectKey=shiftleft-knowledge-hub
sonar.organization=shiftleft
sonar.host.url=https://sonarcloud.io

sonar.sources=backend/src/main/java,frontend/src
sonar.tests=backend/src/test/java
sonar.java.binaries=backend/target/classes

sonar.exclusions=**/api/dto/**,**/domain/**,**/*Repository.*,**/config/**,**/*Application.*,frontend/src/locale/**,frontend/src/styles.css,frontend/src/tailwind.src.css

sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.java.source=21
