sonar.projectKey=HomieEddy_shift-left-hub
sonar.organization=homieeddy
sonar.host.url=https://sonarcloud.io

sonar.sources=backend/src/main/java,frontend/src
sonar.tests=backend/src/test/java
sonar.java.binaries=backend/target/classes

sonar.exclusions=**/api/dto/**,**/domain/**,**/*Repository.*,**/config/**,**/*Application.*,frontend/src/locale/**,frontend/src/styles.css,frontend/src/tailwind.src.css,e2e/**

sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S3735
sonar.issue.ignore.multicriteria.e1.resourceKey=frontend/src/**/*.ts

sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.java.source=21
