DO $$
BEGIN
    CREATE EXTENSION IF NOT EXISTS vector;
EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'vector extension unavailable (pgvector may be pre-installed or insufficient privileges): %', SQLERRM;
END;
$$;

CREATE TABLE app_user (
    id UUID NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_app_user PRIMARY KEY (id),
    CONSTRAINT uc_app_user_email UNIQUE (email)
);

CREATE TABLE article (
    id UUID NOT NULL,
    title_en VARCHAR(255) NOT NULL,
    content_en TEXT NOT NULL,
    title_fr VARCHAR(255),
    content_fr TEXT,
    slug VARCHAR(255),
    excerpt TEXT,
    featured_image VARCHAR(255),
    source_ticket_id UUID,
    status VARCHAR(255) NOT NULL,
    view_count INTEGER NOT NULL DEFAULT 0,
    published_at TIMESTAMP WITHOUT TIME ZONE,
    author_id UUID NOT NULL,
    last_editor_id UUID,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    tsv_en TSVECTOR,
    tsv_fr TSVECTOR,
    CONSTRAINT pk_article PRIMARY KEY (id),
    CONSTRAINT uc_article_slug UNIQUE (slug),
    CONSTRAINT uc_article_source_ticket UNIQUE (source_ticket_id),
    CONSTRAINT fk_article_author FOREIGN KEY (author_id) REFERENCES app_user(id),
    CONSTRAINT fk_article_last_editor FOREIGN KEY (last_editor_id) REFERENCES app_user(id)
);

CREATE TABLE tag (
    id UUID NOT NULL,
    name_en VARCHAR(255) NOT NULL,
    name_fr VARCHAR(255) NOT NULL,
    color VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_tag PRIMARY KEY (id)
);

CREATE TABLE article_tag (
    article_id UUID NOT NULL,
    tag_id UUID NOT NULL,
    CONSTRAINT pk_article_tag PRIMARY KEY (article_id, tag_id),
    CONSTRAINT fk_article_tag_article FOREIGN KEY (article_id) REFERENCES article(id),
    CONSTRAINT fk_article_tag_tag FOREIGN KEY (tag_id) REFERENCES tag(id)
);

CREATE TABLE ticket (
    id UUID NOT NULL,
    ticket_number VARCHAR(9) NOT NULL,
    user_id UUID NOT NULL,
    status VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    urgency VARCHAR(255) NOT NULL,
    issue TEXT NOT NULL,
    shift_left_context JSONB,
    assigned_to_id UUID,
    resolved_by_id UUID,
    resolution_notes TEXT,
    is_knowledge_gap BOOLEAN DEFAULT FALSE,
    resolved_at TIMESTAMP WITHOUT TIME ZONE,
    cancelled_at TIMESTAMP WITHOUT TIME ZONE,
    cancel_reason TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_ticket PRIMARY KEY (id),
    CONSTRAINT uc_ticket_number UNIQUE (ticket_number),
    CONSTRAINT fk_ticket_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT fk_ticket_assigned_to FOREIGN KEY (assigned_to_id) REFERENCES app_user(id),
    CONSTRAINT fk_ticket_resolved_by FOREIGN KEY (resolved_by_id) REFERENCES app_user(id)
);

CREATE TABLE ticket_number_sequence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    next_number INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT pk_ticket_number_sequence PRIMARY KEY (id)
);

CREATE TABLE work_note (
    id UUID NOT NULL,
    ticket_id UUID NOT NULL,
    author_id UUID NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_work_note PRIMARY KEY (id),
    CONSTRAINT fk_work_note_ticket FOREIGN KEY (ticket_id) REFERENCES ticket(id),
    CONSTRAINT fk_work_note_author FOREIGN KEY (author_id) REFERENCES app_user(id)
);

CREATE TABLE ai_config (
    id UUID NOT NULL,
    llm_provider VARCHAR(255),
    ollama_endpoint_url VARCHAR(255),
    openai_api_key VARCHAR(255),
    chat_model_name VARCHAR(255),
    embedding_model_name VARCHAR(255),
    similarity_threshold DOUBLE PRECISION,
    embedding_dimension INTEGER,
    CONSTRAINT pk_ai_config PRIMARY KEY (id)
);

CREATE TABLE vector_store (
    id UUID NOT NULL,
    content TEXT,
    metadata JSONB,
    embedding vector(768),
    CONSTRAINT pk_vector_store PRIMARY KEY (id)
);

-- tsvector generated columns and trigger
ALTER TABLE article
    ADD COLUMN IF NOT EXISTS tsv_en TSVECTOR;

ALTER TABLE article
    ADD COLUMN IF NOT EXISTS tsv_fr TSVECTOR;

CREATE OR REPLACE FUNCTION update_article_tsv()
RETURNS TRIGGER AS $$
BEGIN
    NEW.tsv_en := to_tsvector('english', COALESCE(NEW.title_en, '') || ' ' || COALESCE(NEW.content_en, ''));
    NEW.tsv_fr := to_tsvector('french', COALESCE(NEW.title_fr, '') || ' ' || COALESCE(NEW.content_fr, ''));
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger WHERE tgname = 'trigger_article_tsv'
    ) THEN
        CREATE TRIGGER trigger_article_tsv
        BEFORE INSERT OR UPDATE OF title_en, content_en, title_fr, content_fr
        ON article
        FOR EACH ROW
        EXECUTE FUNCTION update_article_tsv();
    END IF;
END;
$$;

-- GIN indexes for full-text search
CREATE INDEX IF NOT EXISTS idx_article_tsv_en ON article USING GIN (tsv_en);
CREATE INDEX IF NOT EXISTS idx_article_tsv_fr ON article USING GIN (tsv_fr);

-- ivfflat index for vector search
CREATE INDEX IF NOT EXISTS idx_vector_store_embedding ON vector_store USING ivfflat (embedding vector_cosine_ops);

-- Additional query performance indexes
CREATE INDEX IF NOT EXISTS idx_ticket_status_category_urgency ON ticket(status, category, urgency);
CREATE INDEX IF NOT EXISTS idx_work_note_ticket_id ON work_note(ticket_id);
CREATE INDEX IF NOT EXISTS idx_article_status_published_at ON article(status, published_at);
CREATE INDEX IF NOT EXISTS idx_article_author_id ON article(author_id);
CREATE INDEX IF NOT EXISTS idx_user_role ON app_user(role);
